stages:
  - build-dev
  - deploy-dev

build-dev:
  stage: build-dev
  script:
    - docker-compose -f docker-compose-build.yml up
    - cp -R .next /opt/tceam_frontend
  tags:
    - vm121_tceam_front
  only:
    - develop

deploy-dev:
  stage: deploy-dev
  script:
    - docker-compose -f docker-compose-deploy.yml up -d --force-recreate
  tags:
    - vm121_tceam_front
  only:
    - develop
  dependencies:
    - build-dev

